SELECT * FROM ARTIST;
SELECT * FROM "MEMBER";
SELECT * FROM QUESTION;
SELECT * FROM QUESTION_CATEGORY;
SELECT * FROM REPORT;


COMMIT;

----------------------------------------------
UPDATE ARTIST
SET ARTIST_REG = 'Y'
WHERE MEMBER_NO = 84;

SELECT 
    M.MEMBER_NO, 
    M.MEMBER_NAME, 
    SUM(P.PAY_AMOUNT) AS TOTAL_PAY_AMOUNT
FROM "MEMBER" M
LEFT JOIN PAYMENT_RECORD P 
    ON P.MEMBER_NO = M.MEMBER_NO
WHERE M.ARTIST_REG = 'N'
  AND M.MEMBER_DEL_FL = 'N'
GROUP BY M.MEMBER_NO, M.MEMBER_NAME;

SELECT * FROM ARTIST;

INSERT INTO PAYMENT_RECORD
VALUES(2,1,'1700000', CURRENT_DATE,'현장결제',1,3 );
	 

SELECT * FROM REPORT;
	  
/*신고 목록*/
INSERT INTO REPORT
VALUES(SEQ_REPORT_NO.NEXTVAL, 2, 14, 1, '욕설',DEFAULT,DEFAULT,DEFAULT);
INSERT INTO REPORT
VALUES(SEQ_REPORT_NO.NEXTVAL, 2, 14, 1, '욕설',DEFAULT,DEFAULT,DEFAULT);
INSERT INTO REPORT
VALUES(SEQ_REPORT_NO.NEXTVAL, 2, 14, 1, '욕설',DEFAULT,DEFAULT,DEFAULT);	   
	 
UPDATE
	ARTIST
SET
	ARTIST_REG = 'N'
WHERE
	ARTIST_REG = 'Y'
	AND MEMBER_NO = 3;

UPDATE "MEMBER"
SET MEMBER_PENALTY = 31
WHERE MEMBER_NO = 8
AND MEMBER_NO IN (
  SELECT M.MEMBER_NO
  FROM "MEMBER" M
  LEFT JOIN ARTIST A ON A.MEMBER_NO = M.MEMBER_NO
 	WHERE A.ARTIST_REG = 'Y');


UPDATE "MEMBER"
SET MEMBER_PENALTY = 1
WHERE MEMBER_NO = 7;

SELECT *
FROM ARTIST 
WHERE ARTIST_REG = 'N';

UPDATE "MEMBER"
SET MEMBER_PENALTY = '1'
WHERE MEMBER_PENALTY = '31'
AND MEMBER_NO = 8;

SELECT * FROM "MEMBER";
SELECT * FROM ARTIST;

UPDATE "MEMBER"
SET MEMBER_DEL_FL = 'Y'
WHERE MEMBER_NO = 8;

SELECT
		A.MEMBER_NO AS
		"memberNo",
		A.ARTIST_PROFILE AS "artistProfile",
		A.ARTIST_NICKNAME AS
		"artistNickname",
	  ( SELECT SUM(END_PRICE)
			FROM PIECE P 
			LEFT JOIN AUCTION AU ON P.PIECE_NO = AU.PIECE_NO
			WHERE P.MEMBER_NO = A.MEMBER_NO
	  ) AS "endPrice",
	  
		( 
		SELECT SUM(SELL_PRICE) 
		FROM PIECE P2 
		
		JOIN PIECE_SELL PS 
		ON (P2.PIECE_NO = PS.PIECE_NO)
		
		JOIN PAYMENT_RECORD PR
		ON (P2.PIECE_NO = PR.PIECE_NO)
		
		WHERE P2.MEMBER_NO = A.MEMBER_NO
		) AS "sellPrice"
		
		
		FROM ARTIST A;
	
SELECT
    A.MEMBER_NO AS "memberNo",
    A.ARTIST_PROFILE AS "artistProfile",
    A.ARTIST_NICKNAME AS "artistNickname",
    (
        SELECT SUM(END_PRICE)
        FROM PIECE P
        LEFT JOIN AUCTION AU ON P.PIECE_NO = AU.PIECE_NO
        WHERE P.MEMBER_NO = A.MEMBER_NO
    ) AS "endPrice",
    (
        SELECT SUM(SELL_PRICE)
        FROM PIECE P2
        JOIN PIECE_SELL PS ON (P2.PIECE_NO = PS.PIECE_NO)
        JOIN PAYMENT_RECORD PR ON (P2.PIECE_NO = PR.PIECE_NO)
        WHERE P2.MEMBER_NO = A.MEMBER_NO
    ) AS "sellPrice"
FROM ARTIST A
JOIN MEMBER M ON A.MEMBER_NO = M.MEMBER_NO -- MEMBER 테이블과 JOIN
WHERE M.MEMBER_PENALTY = 1;


SELECT
	R.REPORT_NO
	"reportNo",
	R.MEMBER_NO "memberNo",
	P.PIECE_TITLE AS "pieceName",
	P.SIZE_X || ' x ' || P.SIZE_Y AS "pieceSize",
	A.END_PRICE AS "auctionPrice",
	D.ARTIST_NICKNAME AS "artistNickname"
FROM
	REPORT R
JOIN
	PIECE P ON R.PIECE_NO = P.PIECE_NO
LEFT JOIN AUCTION A
	 ON P.PIECE_NO = A.PIECE_NO
LEFT JOIN ARTIST D
	 ON R.MEMBER_NO = D.MEMBER_NO
WHERE
	R.REPORT_DEL_FL ='N';
	
	
SELECT
	COUNT(*)
FROM
	REPORT R
JOIN PIECE P ON R.PIECE_NO = P.PIECE_NO
LEFT JOIN AUCTION A
	ON P.PIECE_NO = A.PIECE_NO
LEFT JOIN ARTIST D 
	ON R.MEMBER_NO = D.MEMBER_NO
WHERE	R.REPORT_DEL_FL ='N';

SELECT ARTIST_NICKNAME AS "artistNickname"
FROM ARTIST
WHERE ARTIST_REG = 'N';
	
SELECT
   R.REPORT_NO AS "reportNo",
   R.MEMBER_NO "memberNo",
   R.PIECE_NO "pieceNo",
   P.PIECE_TITLE AS "pieceName",
   P.SIZE_X || ' x ' || P.SIZE_Y AS "pieceSize",
   TO_CHAR(END_PRICE, 'FM999,999,999,999') AS "auctionPrice",
   D.ARTIST_NICKNAME AS "artistNickname"
FROM
   REPORT R
JOIN
   PIECE P ON R.PIECE_NO = P.PIECE_NO
LEFT JOIN ARTIST D ON R.MEMBER_NO = D.MEMBER_NO
LEFT JOIN (
   SELECT MAX(END_PRICE) END_PRICE, PIECE_NO
   FROM AUCTION
   GROUP BY PIECE_NO      
   ) A ON (A.PIECE_NO = R.PIECE_NO)
WHERE
     R.REPORT_DEL_FL ='N';
     
 
UPDATE 
	"MEMBER"
SET 
	MEMBER_DEL_FL = 'Y'
WHERE 
	MEMBER_NO IN (
  	SELECT M.MEMBER_NO
  	FROM "MEMBER" M
  	LEFT JOIN ARTIST A ON M.MEMBER_NO = A.MEMBER_NO
  	WHERE A.MEMBER_NO = 2
  	AND A.ARTIST_REG = 'Y'
		);


SELECT 
	REPORT_NO, REPORT_TYPE, REPORT_CONTENT
FROM 
	REPORT
WHERE 
	REPORT_NO =1;

DELETE FROM 
	REPORT
WHERE 
	REPORT_NO=2;


SELECT 
	WORK_NO, W.MEMBER_NO, WORK_DETAIL, ARTIST_NICKNAME, ARTIST_PORTFOLIO 
FROM 
	"WORK" W
LEFT JOIN ARTIST A ON A.MEMBER_NO=W.MEMBER_NO;


UPDATE 
	ARTIST
SET 
	ARTIST_REG='Y'
WHERE
	ARTIST_REG='N';


SELECT  
	NOTICE_NO AS "noticeNo",
	NOTICE_TITLE AS "noticeTitle",
	NOTICE_CONTENT AS "noticeContent", 
	NOTICE_DATE AS "noticeDate", 
	NOTICE_DEL_FL AS "noticeDelFl"
FROM
	NOTICE
WHERE 
	NOTICE_DEL_FL = 'N'
ORDER BY
	NOTICE_DATE DESC;

SELECT 
	QUESTION_NO AS "questionNo", 
	MEMBER_NO AS "memberNo", 
	QUESTION_CONTENT AS "questionContent", 
	QUESTION_DEL_FL AS "questionDelFl", 
	QUESTION_ANS_FL AS "questionAnsFl", 
	QUESTION_ANSWER AS "questionAnswer"
FROM 
		QUESTION
WHERE
	    QUESTION_DEL_FL = 'N'
	AND QUESTION_NO = 5;
	
UPDATE 
	QUESTION
SET 
	QUESTION_DEL_FL = 'Y'
WHERE 
	QUESTION_NO = 14
AND QUESTION_DEL_FL = 'N';

DELETE FROM QUESTION
WHERE QUESTION_NO = 2;


UPDATE 
	QUESTION
SET 
  QUESTION_ANS_FL = 'Y',
  QUESTION_ANSWER = '호호'
WHERE 
    QUESTION_NO = 4
AND QUESTION_ANS_FL = 'N';
     
SELECT 
QUESTION_NO AS "Q.questionNo", 
MEMBER_NO AS "Q.memberNo", 
Q.QUESTION_CONTENT AS "questionContent", 
Q.QUESTION_DEL_FL AS "questionDelFl", 
Q.QUESTION_ANS_FL AS "questionAnsFl", 
Q.QUESTION_ANSWER AS "questionAnswer",
C.QUESTION_CATEGORY_NAME AS "questionCategoryName"
FROM 
	QUESTION Q
LEFT JOIN 
	QUESTION_CATEGORY C ON Q.QUESTION_NO = C.QUESTION_NO
WHERE
  QUESTION_DEL_FL = 'N'
AND
  QUESTION_ANS_FL = 'N';



SELECT
	R.REPORT_NO AS "reportNo",
R.MEMBER_NO AS "memberNo",
P.PIECE_TITLE AS "pieceName",
R.REPORT_DATE,
P.SIZE_X || ' x ' || P.SIZE_Y AS "pieceSize",
 TO_CHAR(A.END_PRICE, 'FM999,999,999,999,999,999') AS "auctionPrice",
D.ARTIST_NICKNAME AS "artistNickname",
R.PIECE_NO AS "pieceNo",
P.PIECE_RENAME AS "pieceRename"
FROM
	REPORT R
JOIN
	PIECE P ON R.PIECE_NO = P.PIECE_NO
	LEFT JOIN AUCTION A ON P.PIECE_NO = A.PIECE_NO
	LEFT JOIN ARTIST D ON R.MEMBER_NO = D.MEMBER_NO
WHERE
R.REPORT_DEL_FL ='N'
		ORDER BY REPORT_DATE DESC;
	

UPDATE
	MEMBER
SET 
	MEMBER_DEL_FL = 'Y'
WHERE 
	MEMBER_NO = 27;


SELECT
	R.REPORT_NO AS "reportNo",
	R.MEMBER_NO AS "memberNo",
	P.PIECE_TITLE AS "pieceName",
	R.REPORT_DATE,
	P.SIZE_X || ' x ' || P.SIZE_Y AS "pieceSize",
	D.ARTIST_NICKNAME AS "artistNickname",
	R.PIECE_NO AS "pieceNo",
	P.PIECE_RENAME AS "pieceRename"
FROM
	REPORT R
JOIN
	PIECE P ON R.PIECE_NO = P.PIECE_NO
LEFT JOIN 
	ARTIST D ON R.MEMBER_NO = D.MEMBER_NO
WHERE
R.REPORT_DEL_FL ='N'
ORDER BY REPORT_DATE DESC;

SELECT
	R.REPORT_NO AS "reportNo",
	R.MEMBER_NO AS "memberNo",
	P.PIECE_TITLE AS "pieceName",
	R.REPORT_DATE,
	P.SIZE_X || ' x ' || P.SIZE_Y AS "pieceSize",
	D.ARTIST_NICKNAME AS "artistNickname",
	R.PIECE_NO AS "pieceNo",
	P.PIECE_RENAME AS "pieceRename"
FROM
	REPORT R
JOIN
	PIECE P ON R.PIECE_NO = P.PIECE_NO
LEFT JOIN 
	ARTIST D ON R.MEMBER_NO = D.MEMBER_NO
WHERE
R.REPORT_DEL_FL ='N'
ORDER BY REPORT_DATE DESC;
	
INSERT INTO "ARTIST"
VALUES(
	33,
	'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/profile%profile33.jfif?alt=media',
'호호',
'https://firebasestorage.googleapis.com/v0/b/odagirijoe-3e3a4.firebasestorage.app/o/portfolio%2Fportpolio33.html?alt=media',
'11111111111',
	1,
	DEFAULT
);
COMMIT;

SELECT * FROM MEMBER;
