DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR(50)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(100)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL,
	"MEMBER_IMG"	VARCHAR(50)		NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디(ID)';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호(PW)';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일(EMAIL)';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임(중복 X)';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호(-제외)';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴 여부 (N,Y)';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '가입일';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한(1:일반, 2: 모임 관리자, 3:서버 관리자)';

COMMENT ON COLUMN "MEMBER"."MEMBER_IMG" IS '회원 이미지';

DROP TABLE "GROUP";

CREATE TABLE "GROUP" (
	"GROUP_NO"	NUMBER		NOT NULL,
	"GROUP_NAME"	NVARCHAR2(500)		NOT NULL,
	"GROUP_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"GROUP_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"GROUP_INTRODUCE"	VARCHAR2(4000)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_LIST_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"GROUP_MAIN_IMG"	VARCHAR2(300)		NULL,
	"GROUP_HEADER_IMG"	VARCHAR2(300)		NULL
);

COMMENT ON COLUMN "GROUP"."GROUP_NO" IS '모임 번호(SEQ_GROUP_NO)';

COMMENT ON COLUMN "GROUP"."GROUP_DATE" IS '모임 생성일';

COMMENT ON COLUMN "GROUP"."GROUP_DEL_FL" IS '모임삭제여부(N,Y)';

COMMENT ON COLUMN "GROUP"."GROUP_INTRODUCE" IS '모임 소개글';

COMMENT ON COLUMN "GROUP"."CATEGORY_NO" IS '카테고리 번호 (SEQ_CATEGORY_NO)';

COMMENT ON COLUMN "GROUP"."CATEGORY_LIST_NO" IS '카테고리 리스트 번호(SEQ_CATEGORY_LIST_NO)';

COMMENT ON COLUMN "GROUP"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "GROUP"."GROUP_MAIN_IMG" IS '모임 대표 이미지';

COMMENT ON COLUMN "GROUP"."GROUP_HEADER_IMG" IS '모임 상단 이미지';

COMMENT ON COLUMN "GROUP"."GROUP_MAX_POPULATION" IS '모임 상단 이미지';

DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_TYPE_CODE"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '마지막 수정일';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '삭제 여부(N.Y)';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "BOARD"."BOARD_TYPE_CODE" IS '게시판 종류 코드 번호';

DROP TABLE "COMMENT";

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"PARENT_COMMENT_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호(SEQ_COMMENT_NO)';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제 여부(N,Y)';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

COMMENT ON COLUMN "COMMENT"."PARENT_COMMENT_NO" IS '부모 댓글 번호';

DROP TABLE "CATEGORY";

CREATE TABLE "CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	NVARCHAR2(30)		NOT NULL,
	"CATEGORY_IMG"	NVARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NO" IS '카테고리 번호 (SEQ_CATEGORY_NO)';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NAME" IS '카테고리 이름';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_IMG" IS '카테고리 이미지 경로';

DROP TABLE "SCHEDULE";

CREATE TABLE "SCHEDULE" (
	"SCHEDULE_NO"	NUMBER		NOT NULL,
	"LOCATION"	NVARCHAR2(150)		NOT NULL,
	"GROUP_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"LOCATION_ADDRESS"	NVARCHAR2(150)		NOT NULL,
	"COST"	NUMBER	DEFAULT 0	NOT NULL,
	"GROUP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SCHEDULE"."SCHEDULE_NO" IS '일정 번호';

COMMENT ON COLUMN "SCHEDULE"."LOCATION" IS '위치';

COMMENT ON COLUMN "SCHEDULE"."GROUP_DATE" IS '모임 날짜(default current date)';

COMMENT ON COLUMN "SCHEDULE"."LOCATION_ADDRESS" IS '주소';

COMMENT ON COLUMN "SCHEDULE"."COST" IS '비용(DEFAULT 0)';

COMMENT ON COLUMN "SCHEDULE"."GROUP_NO" IS '모임 번호(SEQ_GROUP_NO)';

DROP TABLE "CHAT";

CREATE TABLE "CHAT" (
	"CHAT_NO"	NUMBER		NOT NULL,
	"CHAT_CONTENT"	NVARCHAR2(1000)		NOT NULL,
	"CHAT_WRITE_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"GROUP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHAT"."CHAT_NO" IS '채팅 번호(SEQ_CHAT_NO)';

COMMENT ON COLUMN "CHAT"."CHAT_CONTENT" IS '채팅 내용';

COMMENT ON COLUMN "CHAT"."CHAT_WRITE_DATE" IS '채팅한 시간';

COMMENT ON COLUMN "CHAT"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "CHAT"."GROUP_NO" IS '모임 번호(SEQ_GROUP_NO)';

DROP TABLE "LIKE";

CREATE TABLE "LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "LIKE"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

DROP TABLE "BOARD_IMG";

CREATE TABLE "BOARD_IMG" (
	"BOARD_IMG_NO"	NUMBER		NOT NULL,
	"BOARD_IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"BOARD_IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"BOARD_IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"BOARD_IMG_ORDER"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_NO" IS '게시판 이미지 번호(SEQ_BOARD_IMG_NO)';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_PATH" IS '게시판 이미지 요청 경로';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_ORIGINAL_NAME" IS '게시판 이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_RENAME" IS '게시판 이미지 변경명';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_IMG_ORDER" IS '게시판 이미지 순서';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호(SEQ_BOARD_NO)';

DROP TABLE "MEMBER_GROUP";

CREATE TABLE "MEMBER_GROUP" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"GROUP_NO"	NUMBER		NOT NULL,
	"MEMBER_GROUP_ENROLL_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"MEMBER_GROUP_BAN"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_GROUP_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER_GROUP"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER_GROUP"."GROUP_NO" IS '모임 번호(SEQ_GROUP_NO)';

COMMENT ON COLUMN "MEMBER_GROUP"."MEMBER_GROUP_ENROLL_DATE" IS '모임별 회원 가입일';

COMMENT ON COLUMN "MEMBER_GROUP"."MEMBER_GROUP_BAN" IS '모임별 탈퇴된 회원(N,Y)';

COMMENT ON COLUMN "MEMBER_GROUP"."MEMBER_GROUP_DEL_FL" IS '모임별 나간 회원(N,Y)';

DROP TABLE "CATEGORY_LIST";

CREATE TABLE "CATEGORY_LIST" (
	"CATEGORY_LIST_NO"	NUMBER		NOT NULL,
	"CATEGORY_LIST_NAME"	NVARCHAR2(30)		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CATEGORY_LIST"."CATEGORY_LIST_NO" IS '카테고리 리스트 번호(SEQ_CATEGORY_LIST_NO)';

COMMENT ON COLUMN "CATEGORY_LIST"."CATEGORY_LIST_NAME" IS '카테고리 리스트 이름';

COMMENT ON COLUMN "CATEGORY_LIST"."CATEGORY_NO" IS '카테고리 번호 (SEQ_CATEGORY_NO)';

DROP TABLE "BOARD_TYPE";

CREATE TABLE "BOARD_TYPE" (
	"BOARD_TYPE_CODE"	NUMBER		NOT NULL,
	"BOARD_NAME"	NVARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_CODE" IS '게시판 종류 코드 번호';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NAME" IS '게시판 이름';

DROP TABLE "INVITE";

CREATE TABLE "INVITE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"GROUP_NO"	NUMBER		NOT NULL,
	"INVITE_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"INVITE_REQ_TIME"	DATE	DEFAULT CURRENT_DATE	NOT NULL
);

COMMENT ON COLUMN "INVITE"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "INVITE"."GROUP_NO" IS '모임 번호(SEQ_GROUP_NO)';

COMMENT ON COLUMN "INVITE"."INVITE_DEL_FL" IS '수락 여부(N,Y)';

COMMENT ON COLUMN "INVITE"."INVITE_REQ_TIME" IS '가입요청시간';

DROP TABLE "SCHEDULE_MEMBER";

CREATE TABLE "SCHEDULE_MEMBER" (
	"SCHEDULE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"GROUP_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "SCHEDULE_MEMBER"."SCHEDULE_NO" IS '일정 번호';

COMMENT ON COLUMN "SCHEDULE_MEMBER"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "SCHEDULE_MEMBER"."GROUP_NO" IS '모임 번호(SEQ_GROUP_NO)';


ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "GROUP" ADD CONSTRAINT "PK_GROUP" PRIMARY KEY (
	"GROUP_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY (
	"SCHEDULE_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CHAT_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"BOARD_IMG_NO"
);

ALTER TABLE "MEMBER_GROUP" ADD CONSTRAINT "PK_MEMBER_GROUP" PRIMARY KEY (
	"MEMBER_NO",
	"GROUP_NO"
);

ALTER TABLE "CATEGORY_LIST" ADD CONSTRAINT "PK_CATEGORY_LIST" PRIMARY KEY (
	"CATEGORY_LIST_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_TYPE_CODE"
);

ALTER TABLE "INVITE" ADD CONSTRAINT "PK_INVITE" PRIMARY KEY (
	"MEMBER_NO",
	"GROUP_NO"
);


ALTER TABLE "GROUP" ADD CONSTRAINT "FK_CATEGORY_TO_GROUP_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "CATEGORY" (
	"CATEGORY_NO"
);

ALTER TABLE "GROUP" ADD CONSTRAINT "FK_CATEGORY_LIST_TO_GROUP_1" FOREIGN KEY (
	"CATEGORY_LIST_NO"
)
REFERENCES "CATEGORY_LIST" (
	"CATEGORY_LIST_NO"
);

ALTER TABLE "GROUP" ADD CONSTRAINT "FK_MEMBER_TO_GROUP_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_TYPE_CODE"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_TYPE_CODE"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_MEMBER_TO_COMMENT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY (
	"PARENT_COMMENT_NO"
)
REFERENCES "COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "FK_GROUP_TO_SCHEDULE_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "FK_MEMBER_TO_CHAT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "FK_GROUP_TO_CHAT_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_BOARD_TO_LIKE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "MEMBER_GROUP" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_GROUP_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "MEMBER_GROUP" ADD CONSTRAINT "FK_GROUP_TO_MEMBER_GROUP_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "CATEGORY_LIST" ADD CONSTRAINT "FK_CATEGORY_TO_CATEGORY_LIST_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "CATEGORY" (
	"CATEGORY_NO"
);

ALTER TABLE "INVITE" ADD CONSTRAINT "FK_MEMBER_TO_INVITE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "INVITE" ADD CONSTRAINT "FK_GROUP_TO_INVITE_1" FOREIGN KEY (
	"GROUP_NO"
)
REFERENCES "GROUP" (
	"GROUP_NO"
);

ALTER TABLE "SCHEDULE_MEMBER" ADD CONSTRAINT "FK_SCHEDULE_TO_SCHEDULE_MEMBER_1" FOREIGN KEY (
	"SCHEDULE_NO"
)
REFERENCES "SCHEDULE" (
	"SCHEDULE_NO"
);

ALTER TABLE "SCHEDULE_MEMBER" ADD CONSTRAINT "FK_MEMBER_GROUP_TO_SCHEDULE_MEMBER" FOREIGN KEY (
	"MEMBER_NO", "GROUP_NO"
)
REFERENCES "MEMBER_GROUP" (
	"MEMBER_NO", "GROUP_NO"
);




-----------------------------------------------------------------------------------------
DROP TABLE "NOTIFICATION";

CREATE TABLE "NOTIFICATION" (
	"NOTIFICATION_NO"	NUMBER		NOT NULL,
	"NOTIFICATION_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"NOTIFICATION_CHECK"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"NOTIFICATION_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"NOTIFICATION_GROUP"	VARCHAR(255)		NOT NULL,
	"SEND_MEMBER_NO"	NUMBER		NOT NULL,
	"_MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_NO" IS '알림 번호';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_CONTENT" IS '알림내용';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_CHECK" IS '읽음여부(Y,N)';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_DATE" IS '알림생성 시간';

COMMENT ON COLUMN "NOTIFICATION"."NOTIFICATION_GROUP" IS '보낸 모임';

COMMENT ON COLUMN "NOTIFICATION"."SEND_MEMBER_NO" IS '알림 보낸 회원 번호';

COMMENT ON COLUMN "NOTIFICATION"."_MEMBER_NO" IS '알림받는 회원 번호';

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY (
	"NOTIFICATION_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1" FOREIGN KEY (
	"SEND_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_2" FOREIGN KEY (
	"_MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


-----------------------------------------------------------------------------------------


-- FOREIGN KEY 제약 삭제
ALTER TABLE "GROUP" DROP CONSTRAINT "FK_CATEGORY_LIST_TO_GROUP_1";
ALTER TABLE "GROUP" DROP CONSTRAINT "FK_CATEGORY_TO_GROUP_1";
ALTER TABLE "BOARD" DROP CONSTRAINT "FK_MEMBER_TO_BOARD_1";
ALTER TABLE "BOARD" DROP CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1";
ALTER TABLE "COMMENT" DROP CONSTRAINT "FK_MEMBER_TO_COMMENT_1";
ALTER TABLE "COMMENT" DROP CONSTRAINT "FK_BOARD_TO_COMMENT_1";
ALTER TABLE "COMMENT" DROP CONSTRAINT "FK_COMMENT_TO_COMMENT_1";
ALTER TABLE "SCHEDULE" DROP CONSTRAINT "FK_GROUP_TO_SCHEDULE_1";
ALTER TABLE "CHAT" DROP CONSTRAINT "FK_GROUP_TO_CHAT_1";
ALTER TABLE "CHAT" DROP CONSTRAINT "FK_MEMBER_TO_CHAT_1";
ALTER TABLE "LIKE" DROP CONSTRAINT "FK_MEMBER_TO_LIKE_1";
ALTER TABLE "LIKE" DROP CONSTRAINT "FK_BOARD_TO_LIKE_1";
ALTER TABLE "BOARD_IMG" DROP CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1";
ALTER TABLE "MEMBER_GROUP" DROP CONSTRAINT "FK_MEMBER_TO_MEMBER_GROUP_1";
ALTER TABLE "MEMBER_GROUP" DROP CONSTRAINT "FK_GROUP_TO_MEMBER_GROUP_1";
ALTER TABLE "CATEGORY_LIST" DROP CONSTRAINT "FK_CATEGORY_TO_CATEGORY_LIST_1";
ALTER TABLE "NOTIFICATION" DROP CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1";
ALTER TABLE "NOTIFICATION" DROP CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_2";


-- 테이블 삭제
DROP TABLE "MEMBER";
DROP TABLE "GROUP";
DROP TABLE "BOARD";
DROP TABLE "COMMENT";
DROP TABLE "CATEGORY";
DROP TABLE "SCHEDULE";
DROP TABLE "CHAT";
DROP TABLE "LIKE";
DROP TABLE "CATEGORY_LIST";
DROP TABLE "MEMBER_GROUP";
DROP TABLE "BOARD_IMG";
DROP TABLE "BOARD_TYPE";
DROP TABLE "NOTIFICATION";

/***************************************************************************************/
/***************************************************************************************/




CREATE SEQUENCE SEQ_BOARD_IMG_NO NOCACHE;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_LIST_NO NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;
CREATE SEQUENCE SEQ_GROUP_NO NOCACHE;
CREATE SEQUENCE SEQ_IMG_NO NOCACHE;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;
CREATE SEQUENCE SEQ_SCHEDULE_NO NOCACHE;
CREATE SEQUENCE SEQ_SCHEDULE_NO NOCACHE;
CREATE SEQUENCE SEQ_POPUP_NO NOCACHE;

DROP SEQUENCE SEQ_BOARD_IMG_NO;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_CATEGORY_LIST_NO;
DROP SEQUENCE SEQ_CATEGORY_NO;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_GROUP_NO;
DROP SEQUENCE SEQ_IMG_NO;
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_SCHEDULE_NO;
DROP SEQUENCE SEQ_POPUP_NO;

/***************************************************************************************/
/***************************************************************************************/
DROP TABLE "POPUP";

CREATE TABLE "POPUP" (
	"POPUP_NO"	NVARCHAR2(300)		NOT NULL,
	"POPUP_NAME"	NVARCHAR2(50)		NOT NULL,
	"POPUP_LOCATION"	NVARCHAR2(50)		NOT NULL,
	"POPUP_RENAME"	NVARCHAR2(50)		NOT NULL,
	"POPUP_LEFT"	NUMBER	DEFAULT 0	NOT NULL,
	"POPUP_UP"	NUMBER	DEFAULT 0	NOT NULL,
	"POPUP_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "POPUP"."POPUP_NO" IS '팝업 이미지 번호(SEQ_POPUP_NO)';

COMMENT ON COLUMN "POPUP"."POPUP_NAME" IS '팝업 이름';

COMMENT ON COLUMN "POPUP"."POPUP_LOCATION" IS '팝업이미지요청주소';

COMMENT ON COLUMN "POPUP"."POPUP_RENAME" IS '팝업이미지요청이름';

COMMENT ON COLUMN "POPUP"."POPUP_LEFT" IS '팝업이미지 좌측죄표';

COMMENT ON COLUMN "POPUP"."POPUP_UP" IS '팝업이미지 상단좌표';

COMMENT ON COLUMN "POPUP"."POPUP_DEL_FL" IS '팝업 삭제 여부(N,Y)';

ALTER TABLE "POPUP" ADD CONSTRAINT "PK_POPUP" PRIMARY KEY (
	"POPUP_NO"
);


/***************************************************************************************/
/***************************************************************************************/
/* 2024 10 19 회의내용 첨삭 */

-- MEMBER TABLE
-- MEMBER IM VARCHAR2(3000) 추가
-- MEMBER OUT FL CHAR(1) NOTNULL DEFAULT 'N' 추가

ALTER TABLE "MEMBER" ADD(MEMBER_IM VARCHAR2(3000));
ALTER TABLE "MEMBER" ADD(MEMBER_OUT_FL CHAR(1) DEFAULT 'N');
ALTER TABLE "MEMBER" MODIFY MEMBER_OUT_FL NOT NULL; -- NULL 허용 X
COMMENT ON COLUMN "MEMBER"."MEMBER_IM" IS '회원 자기소개';
COMMENT ON COLUMN "MEMBER"."MEMBER_OUT_FL" IS '정지 여부(N,Y)';
SELECT * FROM "MEMBER";
UPDATE "MEMBER" SET MEMBER_OUT_FL = 'N' WHERE MEMBER_NO  > 0;
UPDATE "MEMBER" SET MEMBER_IM = '셈플회원 입니다.' WHERE MEMBER_NO  > 0;
COMMIT;

-- BOARD TABLE
-- BOARD_NO 추가

ALTER TABLE "BOARD" ADD(GROUP_NO NUMBER);
ALTER TABLE "BOARD" ADD CONSTRAINT "FK_GROUP_TO_BOARD_1"
FOREIGN KEY ("GROUP_NO") REFERENCES "GROUP" ("GROUP_NO");
ALTER TABLE "BOARD" MODIFY GROUP_NO NOT NULL; -- NULL 허용 X
SELECT * FROM "BOARD";
SELECT * FROM "BOARD" WHERE GROUP_NO IS NULL;
UPDATE BOARD 
SET GROUP_NO = 1 WHERE GROUP_NO IS NULL; 

DELETE FROM MEMBER_GROUP
WHERE MEMBER_NO IN (
    SELECT MEMBER_NO
    FROM MEMBER_GROUP
    GROUP BY MEMBER_NO
    HAVING COUNT(GROUP_NO) > 1
);

UPDATE BOARD B
SET B.GROUP_NO = (
    SELECT MIN(MG.GROUP_NO)  -- 또는 MAX(MG.GROUP_NO)
    FROM MEMBER_GROUP MG
    WHERE MG.MEMBER_NO = B.MEMBER_NO
); 

SELECT * FROM "MEMBER_GROUP";
SELECT * FROM "MEMBER_GROUP" WHERE  MEMBER_NO  =1;
SELECT * FROM "MEMBER_GROUP" WHERE  MEMBER_GROUP_BAN = 'Y';
UPDATE "MEMBER_GROUP" SET MEMBER_GROUP_DEL_FL = 'Y' WHERE MEMBER_GROUP_BAN = 'Y';
INSERT INTO "MEMBER_GROUP"
VALUES (1, 11, DEFAULT, DEFAULT,DEFAULT);

-- GROUP TABLE ADD GROUP_MAX_POPULATION
ALTER TABLE "GROUP" ADD(GROUP_MAX_POPULATION NUMBER DEFAULT 20);
UPDATE "GROUP" SET GROUP_MAX_POPULATION = 20;
ALTER TABLE "GROUP" MODIFY GROUP_MAX_POPULATION NOT NULL;
COMMIT;

/***************************************************************************************/
/***************************************************************************************/

SELECT * FROM BOARD
WHERE GROUP_NO =2;

SELECT * FROM BOARD
WHERE GROUP_NO =1;

INSERT INTO "CATEGORY"
VALUES ( SEQ_CATEGORY_NO.NEXTVAL, '액티비티', 'img.JPG');
INSERT INTO "CATEGORY"
VALUES ( SEQ_CATEGORY_NO.NEXTVAL, '문화/여가', 'img.JPG');
INSERT INTO "CATEGORY"
VALUES ( SEQ_CATEGORY_NO.NEXTVAL, '자기개발', 'img.JPG');
INSERT INTO "CATEGORY"
VALUES ( SEQ_CATEGORY_NO.NEXTVAL, '연애', 'img.JPG');

SELECT * FROM CATEGORY;


INSERT INTO "CATEGORY_LIST"
VALUES (SEQ_CATEGORY_LIST_NO.NEXTVAL, '??', 3);

SELECT * FROM CATEGORY_LIST;
COMMIT;

UPDATE CATEGORY_LIST
SET 
	CATEGORY_NO = '2'
WHERE CATEGORY_LIST_NO = 12;


INSERT INTO "GROUP"
VALUES (SEQ_GROUP_NO.NEXTVAL,'셈플그룹5',DEFAULT,DEFAULT,'셈플용 그룹 생성 입니다',1,4,1,NULL, NULL);

UPDATE "GROUP"
SET 
	GROUP_DEL_FL = 'Y'
WHERE GROUP_NO = 9;


SELECT * FROM "GROUP" ORDER BY GROUP_NO ASC;

SELECT
	GROUP_MAIN_IMG,
	GROUP_HEADER_IMG
FROM "GROUP"
WHERE GROUP_NO = 12;

/* 회원 테이블에 샘플 데이터 삽입*/
BEGIN
	FOR I IN 1.. 200 LOOP
		INSERT INTO "MEMBER"
		VALUES(
			SEQ_MEMBER_NO.NEXTVAL,
			'sample' || I,
			'pass01',
			'sample'|| I ||'@gmail.com',
			'닉네임'||I,
			'01012345678',
			DEFAULT,
			DEFAULT,
			1,
			NULL
		);
	END LOOP;
END;

/* 회원-모임 랜덤 가입*/
BEGIN
	FOR I IN 1.. 200 LOOP
		INSERT INTO "MEMBER_GROUP"
		VALUES(
			I,
			CEIL ( DBMS_RANDOM.VALUE(0, 5) ),
			DEFAULT, DEFAULT, DEFAULT
		);
	END LOOP;
END;

ROLLBACK;

SELECT COUNT(*) FROM MEMBER_GROUP;
SELECT * FROM MEMBER_GROUP WHERE GROUP_NO = 9;


/* 게시판 테이블에 샘플 데이터 삽입*/
INSERT INTO BOARD_TYPE VALUES(1, '공지사항');
INSERT INTO BOARD_TYPE VALUES(2, '일반 게시판');
INSERT INTO BOARD_TYPE VALUES(3, '사진 게시판');
BEGIN
	FOR I IN 1.. 2000 LOOP
		INSERT INTO "BOARD"
		VALUES(
			SEQ_BOARD_NO.NEXTVAL,
			'확인용 게시판 글' || I,
			'확인용 게시판 글 내용' || I,
			DEFAULT, NULL, 0, DEFAULT, 
			CEIL ( DBMS_RANDOM.VALUE(0, 199) ),
			CEIL ( DBMS_RANDOM.VALUE(0, 3) )
		);
	END LOOP;
END;

	
SELECT * FROM BOARD;
SELECT * FROM "INVITE";
SELECT COUNT(*) FROM "BOARD";
SELECT COUNT(*) FROM "BOARD" WHERE BOARD_TYPE_CODE = 1;
SELECT COUNT(*) FROM "BOARD" WHERE BOARD_TYPE_CODE = 2;
SELECT COUNT(*) FROM "BOARD" WHERE BOARD_TYPE_CODE = 3;
SELECT * FROM "BOARD" WHERE GROUP_NO =1 AND BOARD_TYPE_CODE =1 ORDER BY BOARD_NO DESC;
SELECT COUNT(*) FROM "BOARD" WHERE GROUP_NO =1 AND BOARD_TYPE_CODE =1 ORDER BY BOARD_NO DESC;

-- 최근 게시글 확인
SELECT
	ROW_NUMBER() OVER (ORDER BY BOARD_NO ASC) "LIKE_CHECK",
	BOARD_NO,
	BOARD_TITLE,
	TO_CHAR(BOARD_WRITE_DATE, 'YYYY-MM-DD') AS "BOARD_WRITE_DATE",
	READ_COUNT,
	BOARD_TYPE_CODE,
	(SELECT COUNT(*) FROM "COMMENT" C WHERE C.BOARD_NO = B.BOARD_NO ) AS "COMMENT_COUNT",
	(SELECT COUNT(*) FROM "LIKE" L WHERE L.BOARD_NO = B.BOARD_NO ) AS "LIKE"
	
FROM
	"BOARD" B
WHERE
	BOARD_DEL_FL = 'N'
AND BOARD_TYPE_CODE = 1
AND GROUP_NO = 1
ORDER BY
	BOARD_NO DESC
FETCH FIRST 15 ROWS ONLY;

-- 인기글 불러오기
SELECT
	ROW_NUMBER() OVER (ORDER BY BOARD_NO ASC) "LIKE_CHECK",
	BOARD_NO,
	BOARD_TITLE,
	TO_CHAR(BOARD_WRITE_DATE, 'YYYY-MM-DD') AS "BOARD_WRITE_DATE",
	READ_COUNT,
	BOARD_TYPE_CODE,
	(SELECT COUNT(*) FROM "COMMENT" C WHERE C.BOARD_NO = B.BOARD_NO ) AS "COMMENT_COUNT",
	(SELECT COUNT(*) FROM "LIKE" L WHERE L.BOARD_NO = B.BOARD_NO ) AS "LIKE_COUNT",
	(SELECT MEMBER_NICKNAME FROM "MEMBER" M WHERE M.MEMBER_NO = B.MEMBER_NO) AS "MEMBER_NICKNAME"
FROM
	"BOARD" B
WHERE
	BOARD_DEL_FL = 'N'
AND BOARD_TYPE_CODE = 2
AND GROUP_NO = 1
AND ( CURRENT_DATE - BOARD_WRITE_DATE ) < 14
ORDER BY
	LIKE_COUNT DESC
FETCH FIRST 15 ROWS ONLY;


-- 모임가입
INSERT INTO "MEMBER_GROUP"
VALUES(
	1,
	4,
	DEFAULT, DEFAULT, DEFAULT);

SELECT COUNT(*) FROM "INVITE" WHERE GROUP_NO = 1;
SELECT MEMBER_NO, GROUP_NO, INVITE_DEL_FL, INVITE_REQ_TIME FROM "INVITE" WHERE GROUP_NO = 1;

-- 가입신청
INSERT INTO "INVITE"
VALUES(
	11,
	2,
	DEFAULT, DEFAULT);

DELETE FROM "INVITE"
WHERE
	MEMBER_NO = 11
AND GROUP_NO = 2;


-----------------------------------------------------------
/*댓글 샘플*/
SELECT COUNT(*) FROM "BOARD" WHERE GROUP_NO = 6;
SELECT * FROM "COMMENT";

SELECT
	COMMENT_NO,
	COMMENT_CONTENT,
	COMMENT_WRITE_DATE,
	C.BOARD_NO,
	(SELECT M.MEMBER_NICKNAME FROM "MEMBER" M WHERE M.MEMBER_NO = C.MEMBER_NO) AS "MEMBER_NICKNAME"
FROM
	"COMMENT" C
JOIN "BOARD" B ON (C.BOARD_NO = B.BOARD_NO)
WHERE
	COMMENT_DEL_FL = 'N'
AND B.GROUP_NO = 2
ORDER BY
	COMMENT_WRITE_DATE DESC
FETCH FIRST 7 ROWS ONLY;

SELECT * FROM "COMMENT" WHERE PARENT_COMMENT_NO IS NOT NULL;
SELECT COUNT(*) FROM "COMMENT";
-- 1게시판 1~700~1048
-- 2게시판 1049~1648~2000
-- 3게시판 2001~2600~3000
-- 4게시판 3001~3600~4000
-- 5게시판 4001~4600~5000
----
BEGIN
	FOR I IN 1.. 400 LOOP
		INSERT INTO "COMMENT"
		VALUES(
			SEQ_COMMENT_NO.NEXTVAL,
			'5모임의 샘플댓글 입니다, ' || I,
			DEFAULT,
			DEFAULT,
			1,
			(SELECT B.BOARD_NO
			 FROM BOARD B
			 WHERE B.GROUP_NO = 5
			 ORDER BY DBMS_RANDOM.VALUE
			 FETCH FIRST 1 ROWS ONLY),
			 --NULL
			 CEIL ( DBMS_RANDOM.VALUE(4000, 4599) )
		);
	END LOOP;
END;

COMMIT;

-----------------------------------------------------------
/*일정 셈플*/
COMMIT;
SELECT * FROM SCHEDULE ORDER BY SCHEDULE_NO ASC;
SELECT * FROM SCHEDULE_MEMBER ORDER BY SCHEDULE_NO ASC;
SELECT * FROM MEMBER_GROUP WHERE GROUP_NO = 1;

INSERT INTO SCHEDULE
VALUES (SEQ_SCHEDULE_NO.NEXTVAL, '중구/명동', TO_DATE(20241104, 'YYYYMMDD'), 'LOCATION_ADRESS10', 12000, 1);
INSERT INTO SCHEDULE
VALUES (SEQ_SCHEDULE_NO.NEXTVAL, '중구/명동', TO_DATE(20241108, 'YYYYMMDD'), 'LOCATION_ADRESS11', 18500, 1);
INSERT INTO SCHEDULE
VALUES (SEQ_SCHEDULE_NO.NEXTVAL, '중구/명동', TO_DATE(20241110, 'YYYYMMDD'), 'LOCATION_ADRESS12', 13500, 1);

-- 일정번호, 회원번호, 그룹번호
INSERT INTO SCHEDULE_MEMBER
VALUES (19, 161, 1);
INSERT INTO SCHEDULE_MEMBER
VALUES (20, 169, 1);
INSERT INTO SCHEDULE_MEMBER
VALUES (22, 197, 1);

SELECT * FROM "STOP";
----------------------------------------------------------

SELECT
	MG.MEMBER_NO,
	MEMBER_ID,
	MEMBER_EMAIL,
	MEMBER_NICKNAME,
	TO_CHAR(ENROLL_DATE, 'YYYY"년"MM"월"DD"일"') "ENROLL_DATE",
	AUTHORITY,
	MEMBER_IMG,
	TO_CHAR(MEMBER_GROUP_ENROLL_DATE, 'YYYY"년"MM"월"DD"일"') "MEMBER_GROUP_ENROLL_DATE"
FROM MEMBER_GROUP MG
JOIN "MEMBER" M ON (MG.MEMBER_NO = M.MEMBER_NO)
WHERE
	MEMBER_DEL_FL = 'N'
AND	MEMBER_OUT_FL = 'N'
AND MG.GROUP_NO = 1
AND MG.MEMBER_GROUP_DEL_FL = 'N'
AND MG.MEMBER_GROUP_BAN = 'N'
AND MEMBER_ID LIKE '%' || 3 || '%';


-----------------------------------------------------
SELECT
	BOARD_IMG_NO,
	BOARD_IMG_PATH,
	BOARD_IMG_ORIGINAL_NAME,
	BOARD_IMG_RENAME,
	BOARD_IMG_ORDER,
	B1.BOARD_NO
FROM BOARD_IMG B2
LEFT JOIN "BOARD" B1 ON (B1.BOARD_NO = B2.BOARD_IMG_NO)
WHERE B1.GROUP_NO = 1;

SELECT *
FROM BOARD_IMG;

SELECT * FROM "MEMBER";

INSERT INTO BOARD_IMG
VALUES(SEQ_BOARD_IMG_NO.NEXTVAL, '/images/groupPhoto/', 'outdoor3.jpg', 'outdoor3.jpg', 1, 3721);



-- 활동이 가장많은 모임 조회하기
-- 모임명 주최자 참가자수 생성일
SELECT
	GROUP_NO,
	GROUP_NAME,
	TO_CHAR(GROUP_DATE, 'YYYY"년"MM"월"DD"일"') "GROUP_DATE",
	(SELECT MEMBER_NICKNAME
	FROM "MEMBER" M
	WHERE M.MEMBER_NO = G.MEMBER_NO) AS "MEMBER_NICKNAME",
	G.MEMBER_NO,
	(SELECT COUNT(*)
	 FROM MEMBER_GROUP MG
	 JOIN "MEMBER" M2 ON (MG.MEMBER_NO = M2.MEMBER_NO)
	 WHERE
	 	MG.GROUP_NO = G.GROUP_NO
	 AND	MEMBER_GROUP_DEL_FL = 'N'
	 AND MEMBER_GROUP_BAN = 'N'
	 AND M2.MEMBER_DEL_FL = 'N'
	 AND M2.MEMBER_OUT_FL = 'N') AS MEMBER_COUNT,
	GROUP_MAX_POPULATION,
	(SELECT COUNT(*)
	 FROM SCHEDULE S
	 WHERE S.GROUP_NO = G.GROUP_NO) AS ACTIVE_COUNT
FROM
	"GROUP" G
WHERE
	GROUP_DEL_FL = 'N'
ORDER BY
	ACTIVE_COUNT DESC
FETCH FIRST 5 ROWS ONLY;


------------------------------------------------
-- 게시글 이미지 셈플 넣기
SELECT BOARD_NO FROM BOARD WHERE GROUP_NO = 1 ORDER BY BOARD_NO DESC;
SELECT * FROM BOARD_IMG JOIN BOARD USING (BOARD_NO) WHERE GROUP_NO = 1 AND BOARD_IMG_ORDER = 0;

INSERT INTO BOARD_IMG
VALUES(
	SEQ_BOARD_IMG_NO.NEXTVAL,
	'/images/groupPhoto/',
	'샘플이미지입니다',
	'20241023043305_00002',
	0,
	3944);
	
UPDATE BOARD_IMG
SET BOARD_IMG_RENAME = BOARD_IMG_RENAME || '.jpg'
WHERE BOARD_IMG_NO = 13;


------------------------------------------------
-- 팝업 이미지 셈플 넣기

INSERT INTO POPUP
VALUES (SEQ_POPUP_NO.NEXTVAL, '1번모임소개', '/images/mainPopup/', '20241023051054_00001.jpg', 20, 20, DEFAULT);

SELECT
	POPUP_NO,
	POPUP_NAME,
	POPUP_LOCATION,
	POPUP_RENAME,
	POPUP_LEFT,
	POPUP_UP,
	POPUP_DEL_FL
FROM POPUP
WHERE POPUP_DEL_FL = 'N';
----------------------------------------------------

CREATE TABLE "STOP" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"STOP_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"STOP_TERM"	NUMBER		NOT NULL,
	"STOP_REASON"	NVARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "STOP"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "STOP"."STOP_DATE" IS '정지 날짜';

COMMENT ON COLUMN "STOP"."STOP_TERM" IS '정지 기간';

COMMENT ON COLUMN "STOP"."STOP_REASON" IS '정지 사유';

ALTER TABLE "STOP" ADD CONSTRAINT "PK_STOP" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "STOP" ADD CONSTRAINT "FK_MEMBER_TO_STOP_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);


SELECT * FROM STOP;
SELECT * FROM BOARD_IMG;


SELECT * FROM REPORT;

-----------------------------------------------
CREATE TABLE "REPORT" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"REPORT_DATE"	DATE	DEFAULT CURRENT_DATE	NOT NULL,
	"REPORT_DETAIL"	NVARCHAR2(300)		NULL,
	"REPORT_NO"	NUMBER		NOT NULL,
	"REPORT_VIEW"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "REPORT"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고 날짜';

COMMENT ON COLUMN "REPORT"."REPORT_DETAIL" IS '신고 사유';

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고 종류(1:댓글, 2:게시글, 3:기타)';

COMMENT ON COLUMN "REPORT"."REPORT_VIEW" IS '신고 조회 여부(N,Y)';

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

SELECT * FROM "MEMBER";

UPDATE "MEMBER"
		SET MEMBER_OUT_FL = 'Y'
		WHERE
		MEMBER_NO=1;

---------------------------------------
SELECT * FROM "MEMBER"
WHERE MEMBER_EMAIL = 'kwth2002hs@naver.com';

INSERT INTO REPORT
VALUES(14, DEFAULT,'욕설했음',1,DEFAULT,2);

SELECT * FROM SCHEDULE;

SELECT * FROM BOARD_IMG;
COMMIT;
SELECT * FROM REPORT;
SELECT * FROM STOP;
SELECT * FROM "MEMBER" WHERE MEMBER_NO = 115;

SELECT * FROM STOP C JOIN "MEMBER" B ON(C.MEMBER_NO = B.MEMBER_NO) WHERE MEMBER_EMAIL = 'sample74@gmail.com';

UPDATE MEMBER
SET MEMBER_DEL_FL = CASE WHEN MEMBER_DEL_FL = 'N' THEN 'Y' ELSE 'N' END
WHERE MEMBER_NO = 115;

	SELECT *
	FROM "MEMBER";
COMMIT;

SELECT
	*
FROM
	REPORT;

UPDATE REPORT
SET REPORT_VIEW = 'y'
WHERE MEMBER_NO = 85;



SELECT
	*
FROM
	REPORT;






INSERT INTO REPORT
VALUES(51, DEFAULT,'나쁜 언어 썼어요오오옹ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ',9,DEFAULT);
COMMIT;

INSERT INTO REPORT
VALUES(78, DEFAULT,'나쁜 언어썻어요 ㅜㅜ', 2, DEFAULT,2);

SELECT * FROM MEMBER_GROUP;

INSERT INTO MEMBER_GROUP
	VALUES(3, 4, DEFAULT,DEFAULT,DEFAULT);

SELECT *
FROM BOARD_IMG BI
LEFT JOIN "BOARD" B ON (BI.BOARD_NO = B.BOARD_NO)
WHERE B.GROUP_NO = 1;


SELECT * FROM;

SELECT * FROM BOARD_IMG;
COMMIT;


SELECT
	BOARD_NO,
	BOARD_TITLE,
	TO_CHAR(BOARD_WRITE_DATE, 'YYYY-MM-DD') AS "BOARD_WRITE_DATE"
FROM BOARD
WHERE
	BOARD_DEL_FL = 'N'
AND GROUP_NO = 1
ORDER BY
	BOARD_WRITE_DATE DESC
FETCH FIRST 5 ROWS ONLY;

SELECT * FROM BOARD
WHERE
GROUP_NO = 2
;
COMMIT;



	