-- TB_USER 테이블 생성
CREATE TABLE TB_TODO(
	TODO_NO     NUMBER CONSTRAINT TB_TODO_PK PRIMARY KEY,
	TODO_TITLE     VARCHAR2(30) NOT NULL,
	TODO_DETAIL     VARCHAR2(30) NOT NULL,
	TODO_COMPLETE   CHAR(1) NOT NULL,
	TODO_TIME DATE DEFAULT CURRENT_DATE
);


DROP TABLE TB_TODO;

CREATE SEQUENCE SEQ_TODO_NO NOCACHE;

-- 샘플 데이터 INSERT
INSERT INTO TB_TODO
VALUES(
	SEQ_TODO_NO.NEXTVAL, 'user01', 'pass01', 'Y', DEFAULT );
INSERT INTO TB_TODO 
VALUES(
	SEQ_TODO_NO.NEXTVAL,'user01', 'pass02', 'N', DEFAULT );
INSERT INTO TB_TODO 
VALUES(
	SEQ_TODO_NO.NEXTVAL, 'user01', 'pass03', 'N', DEFAULT );


COMMIT;

SELECT *FROM TB_TODO;