SELECT
	EMP_ID, 
	EMP_NAME,
	DECODE(SUBSTR(EMP_No,8,1), '1', 'M', '2', 'F') GENDER, 
	SALARY, 
	DEPT_TITLE, 
	JOB_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
JOIN JOB USING(JOB_CODE)
WHERE 
	DECODE(SUBSTR(EMP_No,8,1), '1', 'M', '2', 'F') = 'F'
AND
	SALARY BETWEEN 3000000 AND 4000000
ORDER BY SALARY DESC;


COMMIT;